// Date: 26/02/2013 17:55:07
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelCheval extends ModelBase
{
  //fields
    ModelRenderer patte1;
    ModelRenderer patte2;
    ModelRenderer patte3;
    ModelRenderer patte4;
    ModelRenderer corps;
    ModelRenderer tete;
    ModelRenderer queue;
    ModelRenderer Piece2;
  
  public ModelCheval()
  {
    textureWidth = 64;
    textureHeight = 64;
    setTextureOffset("Piece1.oreille1", 38, 0);
    setTextureOffset("Piece1.oreille2", 38, 0);
    setTextureOffset("Piece2.cou", 0, 17);
    
      patte1 = new ModelRenderer(this, 48, 0);
      patte1.addBox(0F, 0F, 0F, 4, 14, 4);
      patte1.setRotationPoint(1F, 10F, -10F);
      patte1.setTextureSize(64, 32);
      patte1.mirror = true;
      setRotation(patte1, 0F, 0F, 0F);
      patte2 = new ModelRenderer(this, 48, 0);
      patte2.addBox(0F, 0F, 0F, 4, 14, 4);
      patte2.setRotationPoint(-5F, 10F, -10F);
      patte2.setTextureSize(64, 32);
      patte2.mirror = true;
      setRotation(patte2, 0F, 0F, 0F);
      patte3 = new ModelRenderer(this, 19, 0);
      patte3.addBox(0F, 0F, 0F, 4, 14, 4);
      patte3.setRotationPoint(1F, 10F, 6F);
      patte3.setTextureSize(64, 32);
      patte3.mirror = true;
      setRotation(patte3, 0F, 0F, 0F);
      patte4 = new ModelRenderer(this, 19, 0);
      patte4.addBox(0F, 0F, 0F, 4, 14, 4);
      patte4.setRotationPoint(-5F, 10F, 6F);
      patte4.setTextureSize(64, 32);
      patte4.mirror = true;
      setRotation(patte4, 0F, 0F, 0F);
      corps = new ModelRenderer(this, 0, 32);
      corps.addBox(0F, 0F, 0F, 10, 10, 20);
      corps.setRotationPoint(-5F, 2F, -10F);
      corps.setTextureSize(64, 32);
      corps.mirror = true;
      setRotation(corps, 0F, 0F, 0F);
      tete = new ModelRenderer(this, 26, 12);
      tete.addBox(0F, 0F, 0F, 5, 5, 11);
      tete.setRotationPoint(-2.5F, -4F, -19F);
      tete.setTextureSize(64, 32);
      tete.mirror = true;
      setRotation(tete, 0.296706F, 0F, 0F);
      queue = new ModelRenderer(this, 0, 0);
      queue.addBox(0F, 0F, 0F, 3, 14, 2);
      queue.setRotationPoint(-1.5F, 2F, 7.9F);
      queue.setTextureSize(64, 32);
      queue.mirror = true;
      setRotation(queue, 0.3141593F, 0F, 0F);
    Piece2 = new ModelRenderer(this, "Piece2");
    Piece2.setRotationPoint(0F, 0F, 0F);
    setRotation(Piece2, 0F, 0F, 0F);
    Piece2.mirror = true;
    Piece1 = new ModelRenderer(this, "Piece1");
    Piece1.setRotationPoint(0F, 0F, 0F);
    setRotation(Piece1, 0F, 0F, 0F);
    Piece1.mirror = true;
      Piece1.addBox("oreille1", 0F, 0F, 0F, 1, 2, 2);
      Piece1.addBox("oreille2", 0F, 0F, 0F, 1, 2, 2);
      Piece2.addChildModelRenderer(Piece1);
      Piece2.addBox("cou", 0F, 0F, 0F, 4, 7, 6);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    patte1.render(f5);
    patte2.render(f5);
    patte3.render(f5);
    patte4.render(f5);
    corps.render(f5);
    tete.render(f5);
    queue.render(f5);
    Piece2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
