// Date: 07/03/2013 23:24:44
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mod.legendaire45.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCheese extends ModelBase
{
  //fields
    ModelRenderer morceau_8;
    ModelRenderer morceau_7;
    ModelRenderer morceau_6;
    ModelRenderer morceau_5;
    ModelRenderer morceau_4;
    ModelRenderer morceau_3;
    ModelRenderer morceau_2;
    ModelRenderer morceau_1;
  
  public ModelCheese()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      morceau_8 = new ModelRenderer(this, 44, 12);
      morceau_8.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_8.setRotationPoint(-6F, 18F, 0F);
      morceau_8.setTextureSize(64, 32);
      morceau_8.mirror = true;
      setRotation(morceau_8, 0F, 0F, 0F);
      morceau_7 = new ModelRenderer(this, 24, 0);
      morceau_7.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_7.setRotationPoint(-6F, 18F, -6F);
      morceau_7.setTextureSize(64, 32);
      morceau_7.mirror = true;
      setRotation(morceau_7, 0F, 0F, 0F);
      morceau_6 = new ModelRenderer(this, 31, 20);
      morceau_6.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_6.setRotationPoint(-3F, 18F, 0F);
      morceau_6.setTextureSize(64, 32);
      morceau_6.mirror = true;
      setRotation(morceau_6, 0F, 0F, 0F);
      morceau_5 = new ModelRenderer(this, 44, 0);
      morceau_5.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_5.setRotationPoint(-3F, 18F, -6F);
      morceau_5.setTextureSize(64, 32);
      morceau_5.mirror = true;
      setRotation(morceau_5, 0F, 0F, 0F);
      morceau_4 = new ModelRenderer(this, 12, 20);
      morceau_4.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_4.setRotationPoint(0F, 18F, 0F);
      morceau_4.setTextureSize(64, 32);
      morceau_4.mirror = true;
      setRotation(morceau_4, 0F, 0F, 0F);
      morceau_3 = new ModelRenderer(this, 12, 6);
      morceau_3.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_3.setRotationPoint(0F, 18F, -6F);
      morceau_3.setTextureSize(64, 32);
      morceau_3.mirror = true;
      setRotation(morceau_3, 0F, 0F, 0F);
      morceau_2 = new ModelRenderer(this, 0, 12);
      morceau_2.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_2.setRotationPoint(3F, 18F, 0F);
      morceau_2.setTextureSize(64, 32);
      morceau_2.mirror = true;
      setRotation(morceau_2, 0F, 0F, 0F);
      morceau_1 = new ModelRenderer(this, 0, 0);
      morceau_1.addBox(0F, 0F, 0F, 3, 6, 6);
      morceau_1.setRotationPoint(3F, 18F, -6F);
      morceau_1.setTextureSize(64, 32);
      morceau_1.mirror = true;
      setRotation(morceau_1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    morceau_8.render(f5);
    morceau_7.render(f5);
    morceau_6.render(f5);
    morceau_5.render(f5);
    morceau_4.render(f5);
    morceau_3.render(f5);
    morceau_2.render(f5);
    morceau_1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }
  
  public void renderPart(int part)
  {
	  System.out.println(part);
	  float f5 = 0.0625F;
	  if(part<1)
	  {
		    morceau_1.render(f5);
	  }
	  if(part<2)
	  {
		    morceau_2.render(f5);
	  }
	  if(part<3)
	  {
		    morceau_3.render(f5);
	  }
	  if(part<4)
	  {
		    morceau_4.render(f5);
	  }
	  if(part<5)
	  {
		    morceau_5.render(f5);
	  }
	  if(part<6)
	  {
		    morceau_6.render(f5);
	  }
	  if(part<7)
	  {
		    morceau_7.render(f5);
	  }
	  if(part<8)
	  {
		    morceau_8.render(f5);
	  }
  }

}
