// Date: 21/02/2013 14:26:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mod.legendaire45.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCanape extends ModelBase
{
  //fields
    ModelRenderer bord1;
    ModelRenderer bord2;
    ModelRenderer dossier;
    ModelRenderer base;
    ModelRenderer coussin;
  
  public ModelCanape()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      bord1 = new ModelRenderer(this, 26, 4);
      bord1.addBox(0F, 0F, 0F, 16, 10, 3);
      bord1.setRotationPoint(-8F, 14F, 5F);
      bord1.setTextureSize(128, 64);
      bord1.mirror = true;
      setRotation(bord1, 0F, 0F, 0F);
      bord2 = new ModelRenderer(this, 26, 4);
      bord2.addBox(0F, 0F, 0F, 16, 10, 3);
      bord2.setRotationPoint(-8F, 14F, -8F);
      bord2.setTextureSize(128, 64);
      bord2.mirror = true;
      setRotation(bord2, 0F, 0F, 0F);
      dossier = new ModelRenderer(this, 1, 28);
      dossier.addBox(0F, 0F, 0F, 2, 18, 16);
      dossier.setRotationPoint(8.5F, 7F, -8F);
      dossier.setTextureSize(128, 64);
      dossier.mirror = true;
      setRotation(dossier, 0F, 0F, 0.3316126F);
      base = new ModelRenderer(this, 73, 20);
      base.addBox(0F, 0F, 0F, 11, 4, 16);
      base.setRotationPoint(-6F, 20F, -8F);
      base.setTextureSize(128, 64);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      coussin = new ModelRenderer(this, 76, 46);
      coussin.addBox(0F, 0F, 0F, 10, 2, 16);
      coussin.setRotationPoint(-5F, 18F, -8F);
      coussin.setTextureSize(128, 64);
      coussin.mirror = true;
      setRotation(coussin, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    bord1.render(f5);
    bord2.render(f5);
    dossier.render(f5);
    base.render(f5);
    coussin.render(f5);
  }
  
  public void renderAll()
  {
	  float f5 = 0.0625F;
	  bord1.render(f5);
	  bord2.render(f5);
	  dossier.render(f5);
	  base.render(f5);
	  coussin.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

  public void renderAllAdj1()
  {
	  float f5 = 0.0625F;
	  bord2.render(f5);
	  dossier.render(f5);
	  base.render(f5);
	  coussin.render(f5);
  }
  
  public void renderAllAdj2()
  {
	  float f5 = 0.0625F;
	  bord1.render(f5);
	  dossier.render(f5);
	  base.render(f5);
	  coussin.render(f5);
  }
  
  public void renderAllAdjAll()
  {
	  float f5 = 0.0625F;
	  dossier.render(f5);
	  base.render(f5);
	  coussin.render(f5);
  }

}
